allowBuilds:
  '@alicloud/openapi-core': false
  '@google/genai': false
  esbuild: true
  exifreader: false
  protobufjs: false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@theogony/venus-core@0.14.0'
